namespace NineToFive.Game.Entity.Meta {
    public enum MobStat {
        PAD,
        PDR,
        MAD,
        MDR,
        ACC,
        EVA,
        Speed,
        Stun,
        Freeze,
        Poison,
        Seal,
        Darkness,
        MagicUp,
        PGuardUp,
        MGuardUp,
        Doom,
        Web,
        PImmune,
        MImmune,
        Showdown,
        HardSkin,
        Ambush,
        DamagedElemAttr,
        Venom,
        Blind, 
        SealSkill,
        Burned,
        Dazzle,
        PCounter, MCounter,
        Disable,
        RiseByToss,
        BodyPressure,
        Weakness,
        TimeBomb,
        MagicCrash,
        HealByDamage, // = 37
    }
}